#!/bin/bash
	
subtitler > /dev/null && echo Found subtitler || npm i -g subtitler

# Change this to any language of choice
LANG=${1-heb}

find "$PWD" -type f -execdir subtitler --lang $LANG {} --download -n 2 --retries 2  \;
